name: Test build DEB package
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - "foxy"

jobs:
  build-debian:
    runs-on: ARM64
    container: ros:foxy
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt -y update
          sudo apt install -y dh-make fakeroot
      - name: fakeroot
        run: fakeroot debian/rules binary
      - name: Debian file
        id: deb-file-name
        run: |
          cd .. && echo DEB_FILE="$(pwd)/$(find . -name "ros-foxy-clearbot-px4-msgs*.deb" | sed -r 's/^.{2}//')" >> "$GITHUB_OUTPUT"
      - name: Export deb file artifact
        uses: actions/upload-artifact@v3
        with:
          name: built deb file
          path: ${{ steps.deb-file-name.outputs.DEB_FILE }}
          if-no-files-found: error