name: Release DEB package
on:
  release:
    types: [published]

jobs:
  build-debian:
    runs-on: ARM64
    container: ros:foxy
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt -y update
          sudo apt install -y dh-make fakeroot

      - name: fakeroot
        run: fakeroot debian/rules binary

      - name: Debian file
        id: deb-file-name
        run: |
          cd .. && echo DEB_FILE="$(pwd)/$(find . -name "ros-foxy-clearbot-px4-msgs*.deb" | sed -r 's/^.{2}//')" >> "$GITHUB_OUTPUT"
      - name: Upload to aptserver
        env:
          APTSERVER_USER: ${{ secrets.APTSERVER_USER }}
          APTSERVER_PASSWORD: ${{ secrets.APTSERVER_PASSWORD }}
          FILENAME: ${{ steps.deb-file-name.outputs.DEB_FILE }}
        run: cd .. && curl -X POST -u $APTSERVER_USER:$APTSERVER_PASSWORD -F file=@$FILENAME https://aptserver.clearbot.dev/api/files/clearbot-px4-msgs
